_target_: src.gaze_module.GazeModule

solver:
  name: "AdamW"
  momentum: 0.9
  lr: 0.0001
  weight_decay: 0.001
  decay_steps: [10,20]
  decay_gamma: 0.1
  layer_decay: null
  warmup_epochs: 5
  max_epochs: 50
  scheduler: "cosine"
  apply_linear_scaling: True

net:
  _target_: src.models.gat_model.GaT
  encoder: 
    _target_: src.models.gat_model.Swin3D
  head_dict:
    _target_: src.models.gat_model.HeadDict
    names: 
      - gaze 
    modules: 
      - _target_: src.models.gat_model.MLPHead
        hidden_dim: 256 
        num_layers: 1
        out_features: 3
        dropout: 0.0
        _partial_: true

loss: 
  _target_: src.models.losses.AngularLoss
  task_name: [ "gaze" ] # [ "gaze", "head_pose" ]
  task_weight: [ 1.]
  compute_only_2d: False

# compile model for faster training with pytorch 2.0
compile: false
output_path: ${paths.output_dir}