# @package _global_

defaults:
  - data: gaze_combined_pred # choose datamodule with `test_dataloader()` for evaluation
  - model: default
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - logger: csv
  - _self_

data:
  datasets:
    # - ${extras.eyediap}
    - ${extras.gazefollow}
    # - ${extras.vat}
    # - ${extras.vatvideo}
    # - ${extras.childplay}
    #- ${extras.childplayvideo}
  
  batch_size: 120 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
  num_workers: 10
  data_to_cluster: False

task_name: "pred"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation and prediction
ckpt_path: null
